# Generated by Django 4.1.1 on 2022-10-18 19:35

from django.db import migrations, models
import django.db.models.deletion
import operario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=20)),
                ('legajo', models.IntegerField(unique=True)),
                ('categoria', models.CharField(choices=[('Capataz', 'Capataz'), ('Especializado', 'Especializado'), ('Oficial', 'Oficial'), ('Medio Oficial', 'Medio Oficial'), ('Ayudante', 'Ayudante')], max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, default='operario/avatar.jpg', null=True, upload_to=operario.models.custom_upload_to)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('empresa', models.CharField(choices=[('OMSA', 'OMSA'), ('CWI', 'CWI'), ('SUBCONTRATO', 'SUBCONTRATO')], default='CWI', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=4, null=True)),
                ('obra_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.obra')),
            ],
            options={
                'ordering': ['legajo'],
            },
        ),
        migrations.CreateModel(
            name='Presentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.TimeField()),
                ('hora_egreso', models.TimeField()),
                ('observaciones', models.TextField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Vacaciones', 'Vacaciones'), ('ART', 'ART')], max_length=50, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operario.actividad')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operario.dia')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.obra')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operario.operario')),
            ],
        ),
    ]
