# Generated by Django 4.1.1 on 2022-10-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operario', '0008_alter_dia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='slug',
        ),
    ]
