# Generated by Django 4.1.1 on 2022-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operario', '0010_dia_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dia',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='presentismo',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterField(
            model_name='dia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
