# Generated by Django 4.1.1 on 2022-10-17 22:34

from django.db import migrations, models
import django.db.models.deletion
import obra.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('ingenieria_modulo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=50)),
                ('obra_id', models.CharField(max_length=4)),
                ('pisos', models.IntegerField()),
                ('posiciones', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=obra.models.custom_upload_to)),
                ('estado', models.CharField(choices=[('Proxima', 'Proxima'), ('Ejecucion', 'Ejecucion'), ('Terminada', 'Terminada')], max_length=50)),
                ('ingenieria_obra', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=4)),
            ],
            options={
                'ordering': ['obra_id'],
            },
        ),
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=5)),
                ('posicion', models.IntegerField()),
                ('identificador', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='fabrica', max_length=50)),
                ('fecha_montado', models.DateField(blank=True, null=True)),
                ('fecha_recibido', models.DateField(blank=True, null=True)),
                ('anclajes', models.BooleanField(default=False)),
                ('sellados_int', models.BooleanField(default=False)),
                ('lana', models.BooleanField(default=False)),
                ('pintura', models.BooleanField(default=False)),
                ('recibido', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, max_length=50, null=True)),
                ('reposicion', models.BooleanField(default=False)),
                ('reposicion_obs', models.CharField(blank=True, max_length=30, null=True)),
                ('remito', models.IntegerField(blank=True, null=True)),
                ('apto', models.BooleanField(default=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.modulo')),
            ],
            options={
                'verbose_name': 'Montaje',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.obra'),
        ),
    ]
