# Generated by Django 4.1.1 on 2022-11-05 20:14

from django.db import migrations, models
import django.db.models.deletion
import herramienta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('identificador', models.CharField(max_length=30, unique=True)),
                ('categoria', models.CharField(choices=[('Electrica', 'Electrica'), ('Manual', 'Manual'), ('Equipo', 'Equipo')], max_length=50)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Bueno', 'Bueno'), ('Medio', 'Medio'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Baja', 'Baja')], default='Bueno', max_length=50)),
                ('imagen', models.ImageField(blank=True, default='herramienta/avatar.jpg', null=True, upload_to=herramienta.models.custom_upload_to)),
                ('observaciones', models.TextField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True)),
                ('obra_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obra.obra')),
            ],
            options={
                'ordering': ['marca'],
            },
        ),
    ]
