# Generated by Django 4.0.5 on 2022-06-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='links',
            new_name='link',
        ),
    ]
